language: node_js
node_js:
- '6.1'
notifications:
  email: false
branches:
  only:
  - master
install:
- npm install
script:
- npm run build
deploy:
  provider: npm
  email: darnellandries7@gmail.com
  api_key:
    secure: QiIqbpYeKaMbjYoBhfRCwUGUJiw7sgHi+9m/1CWp0OKcf4hF2NLPQJM1G/A05+RkePHaP8mFil6mdXOIJiwNva2AtJICliAsppDsQz2AiMfNp9I0g8G3HaQsIultQZDlS/hre/iVUvohlEVft8q25jpmPBwuSVNgfazQVxxVLgo418FipKHzsXyF1RR7jSYlocvYQf73Ap0vLcByN3L+skXr+VYfAzIcAW9uC/hnOu/Yhc3RX0MWy5p1xt76DDu6xOEpCqg21X2DpYRDb66+7FZZMG8+S7Bxcernge2GFz49b9lgCHTlRdAc9ENMSfIbtk7YphyWoxKsaJErkV1qeltF9tZv1EnIj/tMBg90ziUdEqUd24DMVKbxgiHhbFqlOoKZhplDZXdZuhdab5DkFQG2j4R/VJegTL2Z8ANbK6s3YQjG/SppxswehOYo6pEZQDApWvqtFmF31QtShX3RhOq2OCNK4odzYSu0bEgSYkfmNVJHI8GPr1sCAoxAIwhVbU7iFsekEf5//NrNwsE8JtlI1+jJQzAYirGaPZW+aXg3NIJP3loa+Zyk37L1vLCm/dgH9sK2syupaaRCOIvqKU6gruZbf5p6kTrz3j1YqmygZKIQKaA8xZJN5RBzlHlYmtKgZv0NtxcHJo6JKl62QyVxH4R/CjyYO186wF+sdyY=
  on:
    repo: DJAndries/bookshelf-ez-fetch
  skip_cleanup: true
